import tkinter  
from tkinter import *
class signup:
    signup=Tk()
    signup.title('Signup')
    signup.geometry('350x100')
    signup.configure(bg='lightsteelblue')
    na=tkinter.Entry(signup)
    na.grid(row=1,column=2)
    un=tkinter.Entry(signup)
    un.grid(row=2,column=2)
    ps=tkinter.Entry(signup,show="*")
    ps.grid(row=3,column=2)
    sb=tkinter.Button(signup,text='Submit')
    sb.grid(row=5,column=5)
    nalabel=tkinter.Label(signup,text='Name:',bg='lightsteelblue')
    nalabel.grid(row=1,column=1)
    unlabel=tkinter.Label(signup,text='Username:',bg='lightsteelblue')
    unlabel.grid(row=2,column=1)
    pslabel=tkinter.Label(signup,text='Password:',bg='lightsteelblue')
    pslabel.grid(row=3,column=1)
    cps=tkinter.Entry(signup,show='*')
    cps.grid(row=4,column=2)
    cpslabel=tkinter.Label(signup,text='Confirm Password',bg='lightsteelblue')
    cpslabel.grid(row=4,column=1)
    signup.geometry('350x110')
    signup.configure(bg='lightsteelblue')
    na=tkinter.Entry(signup)
    na.grid(row=1,column=2)
    un=tkinter.Entry(signup)
    un.grid(row=2,column=2)
    ps=tkinter.Entry(signup,show="*")
    ps.grid(row=3,column=2)
    sb=tkinter.Button(signup,text='Submit')
    sb.grid(row=5,column=5)
    nalabel=tkinter.Label(signup,text='Name:',bg='lightsteelblue')
    nalabel.grid(row=1,column=1)
    unlabel=tkinter.Label(signup,text='Username:',bg='lightsteelblue')
    unlabel.grid(row=2,column=1)
    pslabel=tkinter.Label(signup,text='Password:',bg='lightsteelblue')
    pslabel.grid(row=3,column=1)
    cps=tkinter.Entry(signup,show='*')
    cps.grid(row=4,column=2)
    cpslabel=tkinter.Label(signup,text='Confirm Password:',bg='lightsteelblue')
    cpslabel.grid(row=4,column=1)
